### PR TITLE
Tags the bundle with the repository owner before pushing 

### PR DESCRIPTION
**Pull request by squillace**
Soon porter will be able to be tagged directly, but for now I want to whack the tag with the repository owner so that the pushed bundle is owned properly no matter who clones/forks the repo.

### CODE REVIEW

**Comment by garvinmsft** [comment]
@squillace  We need to add in the secret for the package? @phillipgibson

**Comment by phillipgibson** [comment]
repo secret has been updated. workflow currently running.

**Comment by garvinmsft** [comment]
@phillipgibson  seems like password error still persists

**Comment by squillace** [comment]
without merging this PR, the tag on the repo points to `squillace` which will never, ever push. So if this PR seems ok, merge it. you can always revert. If the secret is now in, it'll work.

**Review by garvinmsft — APPROVED** [review]

**Comment by garvinmsft** [comment]
Need someone else to approve for it to go through

**Pull request merged**
